#ifndef SIMPLE_EXAMPLE_DEFINECONSTANTS_H
#define SIMPLE_EXAMPLE_DEFINECONSTANTS_H

#define BIN_MIN_MZ 0 // spectrast uses 10 // why?
#define BIN_MAX_MZ 2000

#define STANDARD_PARENT_UPPER_MZ 1500
#define STANDARD_PARENT_LOWER_MZ 400

#define FLOAT_OUTPUT_PRECISION std::numeric_limits<float>::max_digits10


#endif //SIMPLE_EXAMPLE_DEFINECONSTANTS_H
