#ifndef SIMPLE_EXAMPLE_DEFINECONSTANTS_H
#define SIMPLE_EXAMPLE_DEFINECONSTANTS_H

#define BIN_MIN_MZ 10 // spectrast uses 10 // why?
#define BIN_MAX_MZ 1900

#endif //SIMPLE_EXAMPLE_DEFINECONSTANTS_H
